---
services:
  regbot:
    container_name: regbot
    environment:
      REGBOT_VERSION: 1.17.0
    image: ghcr.io/taminomara/regbot:${REGBOT_VERSION:-1.17.0}
    env_file: /Stacks/queer-bot/config.env
    ports:
      - "8585:8080"
    restart: unless-stopped
    volumes:
      - /Data/queer-bot:/prod_data
    healthcheck:
      test: "curl --fail http://localhost:8581/ || exit 1"
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5s
