---
services:
  regbot:
    container_name: regbot
    image: ghcr.io/taminomara/regbot:1.18.2
    labels:
      grafana_metrics.enable: true
      grafana_metrics.label.environment: production
    restart: unless-stopped
    volumes:
      - /Data/queer-bot:/prod_data
      - /Stacks/queer-bot:/prod_config
    healthcheck:
      test: "curl --fail http://localhost:8080/metrics || exit 1"
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5s
